//! Keeping a document's bibliography inside its own folder.
//!
//! A document that names `/home/you/Zotero/library.bib` only compiles on the
//! computer where that path exists. The fix is a **mirror**: a copy of the
//! bibliography inside the project, which the document points at by a short
//! relative name, and which Zerkalo keeps up to date from the original. Git
//! carries it to every computer.
//!
//! The same machinery writes a **frozen** copy for submission: only the
//! entries a document cites.
//!
//! Both kinds of file begin with a one-line marker comment. That marker is how
//! Zerkalo knows a file is its own to rewrite; a file without one — anything
//! you wrote or exported yourself — is never overwritten.

use std::path::{Path, PathBuf};

const MIRROR: &str = "zerkalo-mirror:";
const FROZEN: &str = "zerkalo-frozen:";

fn is_yaml(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| e.eq_ignore_ascii_case("yaml") || e.eq_ignore_ascii_case("yml"))
}

fn comment_prefix(path: &Path) -> &'static str {
    if is_yaml(path) {
        "#"
    } else {
        "%"
    }
}

fn first_line(path: &Path) -> Option<String> {
    use std::io::BufRead;
    let file = std::fs::File::open(path).ok()?;
    std::io::BufReader::new(file).lines().next()?.ok()
}

fn marker_of(path: &Path, tag: &str) -> Option<String> {
    let line = first_line(path)?;
    let rest = line.trim_start_matches(['%', '#']).trim();
    rest.strip_prefix(tag).map(|r| r.trim().to_string())
}

/// Whether Zerkalo wrote `path` itself (a mirror or a frozen copy), so it is
/// Zerkalo's to rewrite.
pub fn is_ours(path: &Path) -> bool {
    marker_of(path, MIRROR).is_some() || marker_of(path, FROZEN).is_some()
}

pub fn is_frozen(path: &Path) -> bool {
    marker_of(path, FROZEN).is_some()
}

/// Whether `source` sits inside `project_root` — in which case the document
/// can simply point at it and nothing needs mirroring.
pub fn is_inside(project_root: &Path, source: &Path) -> bool {
    let canon = |p: &Path| std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf());
    canon(source).starts_with(canon(project_root))
}

/// The file inside the project that mirrors `source`: an existing mirror of
/// exactly that source if there is one, else a name that is free (or already
/// one of ours). `source` is the bibliography *file* (`library.yml` for a vault).
pub fn mirror_path_for(project_root: &Path, source: &Path) -> PathBuf {
    let ext = if is_yaml(source) { "yaml" } else { "bib" };
    let names = [
        format!("references.{ext}"),
        format!("references-mirror.{ext}"),
    ];
    let want = source.to_string_lossy();
    for name in &names {
        let p = project_root.join(name);
        if marker_of(&p, MIRROR).as_deref() == Some(&*want) {
            return p;
        }
    }
    // Never reuse a file that mirrors some other source: a document may still
    // be pointing at it. Take the first free name.
    for name in &names {
        let p = project_root.join(name);
        if !p.exists() {
            return p;
        }
    }
    (2..)
        .map(|n| project_root.join(format!("references-mirror-{n}.{ext}")))
        .find(|p| !p.exists())
        .expect("an unused name exists")
}

/// If `path` is a mirror Zerkalo made, the original it copies.
pub fn origin_of(path: &Path) -> Option<PathBuf> {
    marker_of(path, MIRROR)
        .filter(|o| !o.is_empty())
        .map(PathBuf::from)
}

/// The existing mirror of `source` in the project, if Zerkalo made one.
pub fn existing_mirror(project_root: &Path, source: &Path) -> Option<PathBuf> {
    let ext = if is_yaml(source) { "yaml" } else { "bib" };
    let want = source.to_string_lossy();
    [
        format!("references.{ext}"),
        format!("references-mirror.{ext}"),
    ]
    .into_iter()
    .map(|n| project_root.join(n))
    .find(|p| marker_of(p, MIRROR).as_deref() == Some(&*want))
}

fn with_marker(target: &Path, tag: &str, what: &str, body: &str) -> String {
    format!(
        "{} {tag} {what}\n{} Generated by Zerkalo — edit the original, not this copy.\n{body}",
        comment_prefix(target),
        comment_prefix(target),
    )
}

/// Makes `target` a current copy of `source`. Writes only if the contents
/// differ, and never over a file that isn't Zerkalo's own. Returns whether it
/// wrote.
pub fn sync(source: &Path, target: &Path) -> std::io::Result<bool> {
    if target.exists() && !is_ours(target) {
        return Err(std::io::Error::new(
            std::io::ErrorKind::AlreadyExists,
            format!(
                "{} is not a Zerkalo copy; leaving it alone",
                target.display()
            ),
        ));
    }
    let body = std::fs::read_to_string(source)?;
    let text = with_marker(target, MIRROR, &source.to_string_lossy(), &body);
    if std::fs::read_to_string(target).ok().as_deref() == Some(text.as_str()) {
        return Ok(false);
    }
    crate::bibliography::write_atomic(target, &text)?;
    Ok(true)
}

/// A free file name beside the project's documents for a frozen copy of the
/// bibliography cited by `doc`.
pub fn frozen_path_for(project_root: &Path, doc: &Path) -> PathBuf {
    let stem = doc
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("document");
    let base = project_root.join(format!("{stem}-references.bib"));
    if !base.exists() || is_ours(&base) {
        return base;
    }
    (2..)
        .map(|n| project_root.join(format!("{stem}-references-{n}.bib")))
        .find(|p| !p.exists() || is_ours(p))
        .expect("an unused name exists")
}

/// Writes `target` holding only the `keys` cited from `source`, as `.bib`.
/// Returns how many entries it holds.
pub fn freeze(
    source: &Path,
    keys: &std::collections::BTreeSet<String>,
    target: &Path,
    doc_name: &str,
) -> Result<usize, String> {
    if target.exists() && !is_ours(target) {
        return Err(format!(
            "{} already exists and isn't a Zerkalo copy.",
            target.display()
        ));
    }
    let exported =
        crate::cited_refs::export_cited(source, keys, crate::cited_refs::RefFormat::Bib)?;
    let text = with_marker(
        target,
        FROZEN,
        &format!("only what {doc_name} cites"),
        &exported.text,
    );
    crate::bibliography::write_atomic(target, &text).map_err(|e| e.to_string())?;
    Ok(exported.count)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(dir: &Path, name: &str, body: &str) -> PathBuf {
        let p = dir.join(name);
        std::fs::write(&p, body).unwrap();
        p
    }

    #[test]
    fn a_mirror_is_a_marked_copy_and_resyncs_only_when_the_original_changes() {
        let proj = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        let src = write(out.path(), "lib.bib", "@book{a, title={A}}\n");
        let target = mirror_path_for(proj.path(), &src);
        assert_eq!(target, proj.path().join("references.bib"));
        assert!(sync(&src, &target).unwrap());
        assert!(is_ours(&target));
        assert!(std::fs::read_to_string(&target)
            .unwrap()
            .ends_with("@book{a, title={A}}\n"));
        assert!(!sync(&src, &target).unwrap(), "unchanged → no write");
        std::fs::write(&src, "@book{a, title={B}}\n").unwrap();
        assert!(sync(&src, &target).unwrap());
        assert_eq!(existing_mirror(proj.path(), &src), Some(target));
    }

    #[test]
    fn a_file_the_person_made_is_never_overwritten() {
        let proj = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        let src = write(out.path(), "lib.bib", "@book{a,}\n");
        let theirs = write(proj.path(), "references.bib", "@book{mine,}\n");
        assert!(sync(&src, &theirs).is_err());
        assert_eq!(std::fs::read_to_string(&theirs).unwrap(), "@book{mine,}\n");
        // The mirror goes to a different name instead.
        assert_eq!(
            mirror_path_for(proj.path(), &src),
            proj.path().join("references-mirror.bib")
        );
    }

    #[test]
    fn two_different_sources_do_not_share_a_mirror() {
        let proj = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        let a = write(out.path(), "a.bib", "@book{a,}\n");
        let b = write(out.path(), "b.bib", "@book{b,}\n");
        let ta = mirror_path_for(proj.path(), &a);
        sync(&a, &ta).unwrap();
        assert_eq!(existing_mirror(proj.path(), &a), Some(ta.clone()));
        assert_eq!(existing_mirror(proj.path(), &b), None);
        // b gets its own file; a's is left for the documents still using it.
        assert_eq!(
            mirror_path_for(proj.path(), &b),
            proj.path().join("references-mirror.bib")
        );
    }

    #[test]
    fn a_yaml_source_gets_a_yaml_mirror_with_a_hash_marker() {
        let proj = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        let src = write(out.path(), "library.yml", "a:\n  type: Book\n");
        let t = mirror_path_for(proj.path(), &src);
        assert_eq!(t, proj.path().join("references.yaml"));
        sync(&src, &t).unwrap();
        assert!(std::fs::read_to_string(&t)
            .unwrap()
            .starts_with("# zerkalo-mirror:"));
        // It is still valid Hayagriva YAML.
        assert!(crate::bibliography::try_load(&t).is_ok());
    }

    #[test]
    fn a_mirrored_bib_still_loads() {
        let proj = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        let src = write(
            out.path(),
            "lib.bib",
            "@book{a, author={Doe, Jane}, title={T}, year={2001}}\n",
        );
        let t = mirror_path_for(proj.path(), &src);
        sync(&src, &t).unwrap();
        let entries = crate::bibliography::try_load(&t).unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].key, "a");
    }

    #[test]
    fn inside_the_project_needs_no_mirror() {
        let proj = tempfile::tempdir().unwrap();
        let inside = write(proj.path(), "refs.bib", "");
        assert!(is_inside(proj.path(), &inside));
        let out = tempfile::tempdir().unwrap();
        assert!(!is_inside(proj.path(), &out.path().join("x.bib")));
    }

    #[test]
    fn freezing_keeps_only_cited_entries_and_never_overwrites_a_foreign_file() {
        let proj = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        let src = write(
            out.path(),
            "lib.bib",
            "@book{a, title={A}}\n@book{b, title={B}}\n@book{c, title={C}}\n",
        );
        let keys: std::collections::BTreeSet<String> = ["a", "c"].map(String::from).into();
        let target = frozen_path_for(proj.path(), Path::new("/x/essay.typ"));
        assert_eq!(target, proj.path().join("essay-references.bib"));
        assert_eq!(freeze(&src, &keys, &target, "essay.typ").unwrap(), 2);
        let text = std::fs::read_to_string(&target).unwrap();
        assert!(text.starts_with("% zerkalo-frozen:"));
        assert!(text.contains("@book{a") && text.contains("@book{c") && !text.contains("@book{b"));
        // Freezing again replaces our own copy; a foreign file at that name is refused.
        assert!(freeze(&src, &keys, &target, "essay.typ").is_ok());
        let theirs = write(proj.path(), "x-references.bib", "@book{mine,}\n");
        assert!(freeze(&src, &keys, &theirs, "x").is_err());
        assert_eq!(
            frozen_path_for(proj.path(), Path::new("/p/x.typ")),
            proj.path().join("x-references-2.bib")
        );
    }
}
